# Generated by Django 5.1.4 on 2024-12-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LiftRight", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plan_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_body", "3-Day Full Body"),
                    ("upper_lower", "4-Day Upper/Lower"),
                    ("push_pull_legs", "6-Day Push/Pull/Legs"),
                ],
                default="full_body",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="goal",
            field=models.CharField(
                blank=True,
                choices=[("gain muscle", "Gain Muscle"), ("lose fat", "Lose Fat")],
                max_length=50,
                null=True,
            ),
        ),
    ]
