# Generated by Django 5.1.3 on 2024-12-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LiftRight", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("female", "Female"), ("male", "Male")],
                max_length=6,
                null=True,
            ),
        ),
    ]
