# Generated by Django 5.1.3 on 2024-12-20 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LiftRight", "0002_user_plan_type_alter_user_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(13)],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(140.0),
                    django.core.validators.MaxValueValidator(250.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30.0),
                    django.core.validators.MaxValueValidator(300.0),
                ],
            ),
        ),
    ]
