# Generated by Django 5.1.3 on 2024-12-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LiftRight", "0003_alter_user_age_alter_user_height_alter_user_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activity_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sedentary", "Sedentary"),
                    ("moderate", "Moderate Activity"),
                    ("active", "Active"),
                ],
                default="full_body",
                max_length=50,
                null=True,
            ),
        ),
    ]
