# Generated by Django 5.1.3 on 2024-12-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LiftRight", "0003_customuser_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gain muscle", "Gain Muscle"),
                    ("lose fat", "Lose Fat"),
                    ("body decomposition", "Body Decomposition"),
                    ("endurance", "Endurance"),
                    ("strength", "Strength"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
