# Generated by Django 5.1.3 on 2024-12-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LiftRight", "0004_user_activity_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activity_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sedentary", "Sedentary"),
                    ("moderate", "Moderate Activity"),
                    ("active", "Active"),
                ],
                default="moderate",
                max_length=50,
                null=True,
            ),
        ),
    ]
