# Generated by Django 5.1.3 on 2024-12-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LiftRight", "0004_alter_customuser_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="body_fat_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
