# Generated by Django 5.1.3 on 2024-12-17 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LiftRight", "0005_customuser_body_fat_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(13)],
            ),
        ),
    ]
