# Generated by Django 5.1.3 on 2024-12-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LiftRight", "0005_alter_user_activity_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("female", "Female"), ("male", "Male")],
                default="female",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="goal",
            field=models.CharField(
                blank=True,
                choices=[("gain muscle", "Gain Muscle"), ("lose fat", "Lose Fat")],
                default="gain muscle",
                max_length=50,
                null=True,
            ),
        ),
    ]
