# Generated by Django 5.1.4 on 2024-12-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LiftRight", "0006_alter_user_gender_alter_user_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="rest_time",
            field=models.DurationField(default="00:01:00"),
        ),
    ]
