# Generated by Django 5.1.4 on 2024-12-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LiftRight", "0007_alter_exercise_rest_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutplan",
            name="created_at",
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="days",
            field=models.TextField(default="{}"),
        ),
    ]
