# Generated by Django 5.1.4 on 2024-12-21 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LiftRight", "0008_remove_workoutplan_created_at_workoutplan_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutplan",
            name="days",
        ),
    ]
