# Generated by Django 5.1.4 on 2024-12-21 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LiftRight", "0009_remove_workoutplan_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="rest_time",
            field=models.DurationField(default=datetime.timedelta(seconds=60)),
        ),
    ]
