# Generated by Django 5.1.4 on 2024-12-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LiftRight", "0010_alter_exercise_rest_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="diet_plan",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="meal_time",
        ),
        migrations.AddField(
            model_name="meal",
            name="name",
            field=models.CharField(default="NULL", max_length=255),
            preserve_default=False,
        ),
    ]
