# Generated by Django 5.1.4 on 2024-12-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LiftRight", "0011_remove_meal_diet_plan_remove_meal_meal_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dietplan",
            name="created_at",
        ),
        migrations.AddField(
            model_name="dietplan",
            name="meals",
            field=models.ManyToManyField(to="LiftRight.meal"),
        ),
    ]
